.de Vb \" Begin verbatim text
.ft CW
.nf
.ne \\$1
..
.de Ve \" End verbatim text
.ft R
.fi
..

.TH i3lock\-extended 1 "APRIL 2024" Linux "User Manuals"

.SH NAME
i3lock\-extended \- improved screen locker

.SH SYNOPSIS
.B i3lock\-extended
.RB [\|\-B
.IR color \|]
.RB [\|\-b\|]
.RB [\|\-C
.IR seconds \|]
.RB [\|\-c
.IR color \|]
.RB [\|\-D\|]
.RB [\|\-E\|]
.RB [\|\-e\|]
.RB [\|\-F
.IR color \|]
.RB [\|\-f\|]
.RB [\|\-G
.IR color \|]
.RB [\|\-i
.IR image.png \|]
.RB [\|\-J
.IR text \|]
.RB [\|\-L\|]
.RB [\|\-n\|]
.RB [\|\-O
.IR color \|]
.RB [\|\-p
.IR pointer\|]
.RB [\|\-R
.IR color \|]
.RB [\|\-r
.IR refresh rate \|]
.RB [\|\-S
.IR size \|]
.RB [\|\-T
.IR template \|]
.RB [\|\-t\|]
.RB [\|\-u\|]
.RB [\|\-v\|]
.RB [\|\-W
.IR halign \|]
.RB [\|\-X
.IR halign \|]
.RB [\|\-x
.IR halign \|]
.RB [\|\-Y
.IR valign \|]
.RB [\|\-y
.IR valign \|]
.RB [\|\-Z
.IR valign \|]

.SH DESCRIPTION
.B i3lock-extended
is a fork of i3lock which is a simple screen locker like slock.
i3lock-extended has all the i3lock features and some additional ones. 
Hence this manual will refer to i3lock-extended only when describing these
additional features. After starting it, you will see a white screen
(you can configure the color/an image). You can return to your screen by
entering your password.

.SH IMPROVEMENTS

.IP \[bu] 2
i3lock forks, so you can combine it with an alias to suspend to RAM (run "i3lock && echo mem > /sys/power/state" to get a locked screen after waking up your computer from suspend to RAM)
.IP \[bu]
You can specify either a background color or a PNG image which will be displayed while your screen is locked.
.IP \[bu]
You can specify whether i3lock should bell upon a wrong password.
.IP \[bu]
i3lock uses PAM and therefore is compatible with LDAP, etc.

.SH EXTENDED FUNCTIONALITY
.B i3lock\-extended
provides the following additional functionality:

.IP \[bu] 2
LED-clock
.IP \[bu]
Digital clock
.IP \[bu]
Elapsed time since activation
.IP \[bu]
Display-text
.IP \[bu]
Count broken-down time until a specific calendar time (absolute time)

.SH OPTIONS
.TP
.BI \-B\  rrggbb \fR,\ \fB\-\-led\-border\-color= rrggbb
The border color of the LED clock.
format: rrggbb (i.e. ff0000 is red). Default: 000000 (black).

.TP
.B \-b, \-\-beep
Enable beeping. Be sure to not do this when you are about to annoy other people,
like when opening your laptop in a boring lecture.

.TP
.BI \-c\  rrggbb \fR,\ \fB\-\-color= rrggbb
Turn the screen into the given color instead of white.
Color must be given in 3-byte. Default: ffffff (white).

.TP
.BI \-C\  seconds \fR,\ \fB\-\-count\-until= seconds
Sets the seconds since the Epoch to count to. date +%s -d ... can be used to
get the Epoch time. Then the following macros will become available for the
display-text parameter: %d - days remaining until the time set,
%h - hours remaining, %m - minutes remaining, %s - seconds remaining,
%S - total amount of seconds remaining. Default: 0 (count until is off).

.TP
.B \-D, \-\-digital\-clock
Display digital clock.

.TP
.B \-\-debug
Enables debug logging.
Note, that this will log the password used for authentication to stdout.

.TP
.B \-E, \-\-elapsed\-time
Display the elapsed time since i3lock-extended was activated.

.TP
.B \-e, \-\-ignore-empty-password
When an empty password is provided by the user, do not validate
it. Without this option, the empty password will be provided to PAM
and, if invalid, the user will have to wait a few seconds before
another try. This can be useful if the XF86ScreenSaver key is used to
put a laptop to sleep and bounce on resume or if you happen to wake up
your computer with the enter key.

.TP
.BI \-F\  rrggbb \fR,\ \fB\-\-led\-off\-color= rrggbb
The color of the off-LED in the LED-clock. Default: 7f7f7f.

.TP
.B \-f, \-\-show-failed-attempts
Show the number of failed attempts, if any.

.TP
.BI \-G\  rrggbb \fR,\ \fB\-\-digital\-clock\-color= rrggbb
The color of the digital-clock (text). Default: 000000 (black).

.TP
.BI \-i\  path \fR,\ \fB\-\-image= path
Display the given PNG image instead of a blank screen.

.TP
.BI \-J\  text \fR,\ \fB\-\-display\-text= text
Display text instead of elapsed time, using the same color and alignment.

.TP
.B \-k, \-\-show-keyboard-layout
Show the current keyboard layout.

.TP
.B \-L, \-\-led\-clock
Display LED-clock.

.TP
.B \-n, \-\-nofork
Don't fork after starting.

.TP
.BI \-O\  rrggbb \fR,\ \fB\-\-led\-on\-color= rrggbb
The color of the on-LED in the LED-clock. Default: ffff00 (yellow).

.TP
.BI \-p\  win|default \fR,\ \fB\-\-pointer= win|default
If you specify "default",
.B i3lock
does not hide your mouse pointer. If you specify "win",
.B i3lock
displays a hardcoded Windows-Pointer (thus enabling you to mess with your
friends by using a screenshot of a Windows desktop as a locking-screen).

.TP
.BI \-R\  rrggbb \fR,\ \fB\-\-elapsed\-time\-color= rrggbb
The color of the elapsed time (text). Default: 000000 (black).

.TP
.BI \-r\  rate \fR,\ \fB\-\-refresh\-rate= rate
Rate is the amount of times per second we refresh the screen. Default: 2.

.TP
.BI \fB\-\-raw= format
Read the image given by \-\-image as a raw image instead of PNG. The argument is the image's format
as <width>x<height>:<pixfmt>. The supported pixel formats are:
\'native', 'rgb', 'xrgb', 'rgbx', 'bgr', 'xbgr', and 'bgrx'.
The "native" pixel format expects a pixel as a 32-bit (4-byte) integer in
the machine's native endianness, with the upper 8 bits unused. Red, green and blue are stored in
the remaining bits, in that order.

.BR Example:
.Vb 6
\&	--raw=1920x1080:rgb
.Ve

.BR
You can use ImageMagick’s
.IR convert(1)
program to feed raw images into i3lock:

.BR
.Vb 6
\&	convert wallpaper.jpg RGB:- | i3lock --raw 3840x2160:rgb --image /dev/stdin
.Ve

This allows you to load a variety of image formats without i3lock having to
support each one explicitly.

.TP
.BI \-S\  size \fR,\ \fB\-\-text\-size= size
The text size for elapsed time, digital clock and display-text. Default: 28.

.TP
.BI \-T\  template \fR,\ \fB\-\-digital\-clock\-template= template
The date(time) template for the digital clock. Default: %H:%M:%S.

.TP
.B \-t, \-\-tiling
If an image is specified (via \-i) it will display the image tiled all over the screen
(if it is a multi-monitor setup, the image is visible on all screens).

.TP
.B \-u, \-\-no-unlock-indicator
Disable the unlock indicator. i3lock will by default show an unlock indicator
after pressing keys. This will give feedback for every keypress and it will
show you the current PAM state (whether your password is currently being
verified or whether it is wrong).

.TP
.B \-v, \-\-version
Display the version of your
.B i3lock

.TP
.BI \-W\  halign \fR,\ \fB\-\-elapsed\-time\-halign= halign
The horizontal alignment for elapsed time and display-text.
Valid halign values: left, center, right. Default: right

.TP
.BI \-X\  halign \fR,\ \fB\-\-led\-clock\-halign= halign
The horizontal alignment for the LED-clock. Default: center

.TP
.BI \-x\  halign \fR,\ \fB\-\-digital\-clock\-halign= halign
The horizontal alignment for the digital clock. Default: left

.TP
.BI \-Y\  valign \fR,\ \fB\-\-led\-clock\-valign= valign
The vertical alignment for the LED-clock.
Valid valign values: top, middle, bottom. Default: bottom

.TP
.BI \-y\  valign \fR,\ \fB\-\-digital\-clock\-valign= valign
The vertical alignment for the digital clock. Default: top

.TP
.BI \-Z\  valign \fR,\ \fB\-\-elapsed\-time\-valign= valign
The vertical alignment for elapsed time and display-text. Default: bottom

.SH DPMS

The \-d (\-\-dpms) option was removed from i3lock in version 2.8. There were
plenty of use-cases that were not properly addressed, and plenty of bugs
surrounding that feature. While features are not normally removed from i3 and
its tools, we felt the need to make an exception in this case.

Users who wish to explicitly enable DPMS only when their screen is locked can
use a wrapper script around i3lock like the following:

.Vb 6
\&	#!/bin/sh
\&	revert() {
\&	  xset dpms 0 0 0
\&	}
\&	trap revert HUP INT TERM
\&	xset +dpms dpms 5 5 5
\&	i3lock -n
\&	revert
.Ve

The \-I (-\-inactivity-timeout=seconds) was removed because it only makes sense with DPMS.

.SH SEE ALSO
.IR xautolock(1)
\- use i3lock as your screen saver

.IR convert(1)
\- feed a wide variety of image formats to i3lock

.SH AUTHOR
Michael Stapelberg <michael+i3lock at stapelberg dot de>

Jan-Erik Rediger <badboy at archlinux.us>

Simeon Simeonov <sgs (AT) pichove (DOT) org>
